### ISSUE TITLE
Eta-decoder fungerer ikke ved blanding af tidsopskrivninger

### ISSUE THREAD

**Issue by oscar4aar** [FysikRevy/FysikRevyTeX#22]
Hvis dum revyst skriver f.x. \eta{"$2:30$ minutter"} så forstår eta-decoderen det tilsydenladende som blot "minutter" (ikke nogle minutter).
Det fungerer fint ved $2:30$ eller $2$ minutter og $30$ sekunder, bare ikke det blandede format

Der er flere revyster der har skrevet den blandede eta i nyere revyer. Dette kan måske bare tilføjes i readme filen at hvem end der har texmaster filen skal bonke folk der skriver forkert format, eller tilføjes til decoderen for at redde de kære rus

**Comment by theunbound** [comment]
Måske løst i 62e8f5b ?

**Comment by oscar4aar** [comment]
Den løser det delvist, nok for mine behov.
That is, tidsdiagrammet angiver rigtig nok f.eks. $2:30$ minutter som $2:30$ i længden af sketchen.
Det viser aktoversigtens tidsestimat dog ikke, den angiver kun 2 minutter

Jeg har leget lidt med det, det virker til at aktoversigten ikke længere benytter sekunder. Selvom jeg angiver f.eks. $2:30$, eller $1,5$ minutter eller $1$ minut og $45$ sekunder. 

Tidsdiagrammet forstår det fuldt ud, bare ikke aktoversigten

**Comment by theunbound** [comment]
Ja, aktoversigten et med vilje lavet til kun at vise minutter. Jeg ved ikke
hvorfor, det er ikke mig der har gjort det.

Hvis du synes, der skal laves om, så lader vi den her issue stå åben. Der
er nok nogen, der ser på det på et tidspunkt... 😉

lør. 16. nov. 2024 12.18 skrev oscar4aar ***@***.***>:

**Comment by oscar4aar** [comment]
Jeg var bare overbevist om at det engang var sekunder med i aktoversigten.
Men det er ikke noget der er vigtigt

Det er ikke noget vigtigt problem, det største problem var det med 6:30 minutter
