### ISSUE TITLE
Flyt til fysikrevys organisation

### ISSUE THREAD

**Issue by theunbound** [FysikRevy/FysikRevyTeX#9]
Hej Kristoffer!

Jeg har samlet ansvaret op for TeXningen i revyen de sidste par år, og har udviklet i min egen fork af fysikrevytex. Men mere relevant, så har jeg lavet en [github-organisation til fysikrevyen](https://github.com/FysikRevy), som jeg forhåbentlig kan få lokket fremtidige tex-ansvarlige ind i. Og så synes jeg, at det vil være praktisk, hvis det er det repository, som kommer frem, når man søger efter “fysikrevytex” frem for det her. Så kan vi lave noget github-voodoo for at få det til at ske?

-Kristoffer

**Comment by kstensbo** [comment]
Hej Kristoffer!

Beklager det langsomme svar! Fedt at du har lavet en organisation - det lyder som en rigtig god plan at bruge den som centrum for udviklingen af FysikRevyTeX. 

Jeg har ikke prøvet den slags før, men det ser ud til, at jeg simpelthen kan overføre dette repo til organisationen. Dog har I allerede et repo af samme navn (gaflet herfra), som ovenikøbet har nyere ændringer. Hvad tænker du er den smarte fremgangsmåde her?

**Comment by theunbound** [comment]
No worries! Jeg har også erratiske svartider ind imellem.

Jeg har flyttet repo'et i organisationen tilbage til min egen konto, så der burde være plads nu.

Tak,

-Kristoffer

**Comment by kstensbo** [comment]
Jeg har lige forsøgt at overføre repoet, men jeg får fejlen `You don’t have the permission to create public repositories on FysikRevy`. Måske kan du tilføje mig til organisationen?

**Comment by kstensbo** [comment]
Awesome! Transfer complete.

**Comment by theunbound** [comment]
Superb!
